receivers:
  syslog:
    udp:
      listen_address: "127.0.0.1:54526"
    protocol: rfc3164
    location: ${env:TZ}

exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: "${env:DT_ENDPOINT}/api/v2/otlp"
    headers:
      Authorization: "Api-Token ${env:DT_API_TOKEN}"

service:
  pipelines:
    logs:
      receivers: [syslog]
      exporters: [debug, otlphttp]
